"""
Apply yellow highlight to all additions made in this session to the albanese report.
Requires the docx to have been generated by pandoc first.
"""
from __future__ import annotations

import sys
from docx import Document
from docx.enum.text import WD_COLOR_INDEX  # type: ignore[attr-defined]

YELLOW = WD_COLOR_INDEX.YELLOW


def highlight_paragraph(para) -> None:
    for run in para.runs:
        run.font.highlight_color = YELLOW


def highlight_from_phrase(para, phrase: str) -> bool:
    """Highlight all runs starting from the run that contains `phrase`."""
    full_text = para.text
    start_idx = full_text.find(phrase)
    if start_idx == -1:
        return False

    pos = 0
    highlighting = False
    for run in para.runs:
        run_end = pos + len(run.text)
        if not highlighting and run_end > start_idx:
            highlighting = True
        if highlighting:
            run.font.highlight_color = YELLOW
        pos = run_end
    return True


# ── phrases that mark the START of additions appended to existing paragraphs ──
APPENDED_PHRASES = [
    # Civilian section
    "Word-embedding analysis on the SZ sub-corpus corroborates this pattern:",
    # Systematization paragraph
    "A WEAT test on editorial framing in the SZ sub-corpus",
    # Dehumanization 1,593 paragraph
    "This finding is independently corroborated at the level of word embeddings:",
    # Death-language paragraph
    "A WEAT test on death language in the SZ sub-corpus",
    # Collective-threat paragraph
    "A WEAT test on violence framing in the SZ sub-corpus",
]

# ── phrases that identify ENTIRELY NEW standalone paragraphs ──
FULL_PARA_PHRASES = [
    "To complement the LLM-based classification, we additionally applied",
    "Word-embedding analysis on the SZ sub-corpus provides systematic corroboration",
    "Badilla, P., Bravo-Marquez, F., & Pérez, J. (2020). WEFE",
    "Caliskan, A., Bryson, J. J., & Narayanan, A. (2017). Semantics",
]

# ── heading text that marks the start of the new Appendix C section ──
APPENDIX_C_HEADING = "APPENDIX C: WEFE Word Sets and Experiment Definitions"


def highlight_table(table) -> None:
    for row in table.rows:
        for cell in row.cells:
            for para in cell.paragraphs:
                highlight_paragraph(para)


def main(docx_path: str) -> None:
    doc = Document(docx_path)
    paras = doc.paragraphs

    in_appendix_c = False

    for para in paras:
        text = para.text.strip()

        # Check if we've entered the new Appendix C section
        if APPENDIX_C_HEADING in text:
            in_appendix_c = True

        # Highlight the entire Appendix C section
        if in_appendix_c:
            highlight_paragraph(para)
            continue

        # Full-paragraph additions
        for phrase in FULL_PARA_PHRASES:
            if text.startswith(phrase[:40]):
                highlight_paragraph(para)
                break

        # Partial (appended) additions
        for phrase in APPENDED_PHRASES:
            if phrase[:40] in text:
                highlight_from_phrase(para, phrase)
                break

    # All tables in this document are Appendix C word-set / experiment tables
    for table in doc.tables:
        highlight_table(table)

    doc.save(docx_path)
    print(f"Saved with yellow highlights: {docx_path}")


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else (
        "reports/computational results and methodology - albanese.docx"
    )
    main(path)
